spring.application.name=VetBackend

# springdoc.swagger-ui.path=/swagger-ui

# Evita que springdoc intente ?deducir? respuestas a partir de ControllerAdvice
springdoc.override-with-generic-response=false

# Para diagnosticar
logging.level.org.springdoc=DEBUG

# Para ver todas las rutas reales
management.endpoints.web.exposure.include=*
